#!/usr/bin/env python
import os, sys, subprocess, datetime

TEMPLATE = """
// Auto generated by version.py

package com.defold.extender;
public class Version {
    public static final String gitVersion = "%(sha1)s";
    public static final String buildTime = "%(buildTime)s";
}
"""


def run(cmd):
	cmd = cmd.split()
	p = subprocess.Popen(cmd, stdout=subprocess.PIPE)
	p.wait()
	if p.returncode != 0:
		return None
	return p.stdout.read()

def get_sha1():
	output = run('git rev-parse --short HEAD')
	if None:
		return None
	return output.strip()


if __name__ == '__main__':
	sha1 = get_sha1()
	buildTime = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

	s = TEMPLATE % {'sha1':sha1, 'buildTime':buildTime}

	outputdir = os.path.dirname(os.path.abspath(__file__))
	output = os.path.join(outputdir, 'Version.java')

	with open(output, 'w') as f:
		f.write(s)
	print("Wrote to", output)
