
extender:
    sdk:
        cache-clear-on-exit: false
    cache:
        enabled: true
        type: LOCAL
        local.basedir: /var/extender/cache/data
        #type: S3
        #s3.bucket: defold-extender-cache-dev

    remote-builder:
        enabled: false
        # This points to the host machine from inside docker
        url: http://host.docker.internal:9010
