services:
  test_builder:
    platform: linux/amd64
    volumes:
      - ./../app/:/app/:ro
      - ./../configs:/etc/defold/extender:ro
      - ./../test-data/sdk:/var/extender/sdk
    entrypoint: ["java","-Xmx4g","-XX:MaxDirectMemorySize=2g","-jar","/app/extender.jar"]
    environment:
      - EXAMPLE_VAR=1
  common_builder:
    platform: linux/amd64
    volumes:
      - ./../app/:/app/:ro
      - ./../app/:/etc/extender/apps/:ro
      - ./../configs:/etc/defold/extender:ro
      - ${DYNAMO_HOME:-./../app/dummy}:/dynamo_home
    entrypoint: ["java","-Xmx4g","-XX:MaxDirectMemorySize=2g","-jar","/app/extender.jar"]
    environment:
      - ${DYNAMO_HOME:+DYNAMO_HOME=/dynamo_home}
      - DM_DEBUG_COMMANDS
      - DM_DEBUG_DISABLE_PROGUARD
      - DM_DEBUG_JOB_FOLDER
      - DM_DEBUG_KEEP_JOB_FOLDER
      - DM_DEBUG_JOB_UPLOAD
  remote_builder:
    extends: common_builder
    command: ["--spring.config.location=classpath:./,file:/etc/defold/extender/", "--spring.profiles.active=local-dev"]
  test_remote_builder:
    extends: test_builder
    command: ["--spring.config.location=classpath:./,file:/etc/defold/extender/", "--spring.profiles.active=local-dev"]