FROM defold/extender-emsdk-2011-env

COPY users/ users/
ADD extender-0.1.0.jar app.jar
ADD manifestmergetool-0.1.0.jar $MANIFEST_MERGE_TOOL

RUN chown extender: /var/extender && \
    chown extender: $(which java) && \
    chown extender: app.jar && \
    chown -R extender: /var/extender/cache

USER extender
ENTRYPOINT ["java","-Xmx2g","-XX:MaxDirectMemorySize=1g","-jar","/app.jar"]