FROM europe-west1-docker.pkg.dev/extender-426409/extender-public-registry/extender-wine-env:1.5.0

ENV NINTENDO_SDK_ROOT_18_3=${PLATFORMSDK_DIR}/nx-18.3.2
ENV SWITCH_SDK_18_FILENAME=nx64-sdk-18.3.2.tar.gz

RUN --mount=type=secret,id=DM_PACKAGES_URL,required=true \
   echo "Switch SDK 18.3.2" && \
   mkdir -p ${NINTENDO_SDK_ROOT_18_3} && \
   wget -q -O - $(cat /run/secrets/DM_PACKAGES_URL)/${SWITCH_SDK_18_FILENAME} | tar xz -C ${NINTENDO_SDK_ROOT_18_3}