FROM defold/extender-base

ARG DM_PACKAGES_URL
ENV PS4_SDK_11_VERSION 11.000
ENV PS4_SDK_11  ${PLATFORMSDK_DIR}/ps4-sdk-${PS4_SDK_11_VERSION}

ENV PS4_SDK_11_FILENAME ps4-sdk-${PS4_SDK_11_VERSION}.tar.gz

RUN \
  echo "PS4 ${PS4_SDK_11_FILENAME}" && \
  mkdir -p ${PS4_SDK_11} && \
  wget -q -O - ${DM_PACKAGES_URL}/${PS4_SDK_11_FILENAME} | tar xz -C ${PS4_SDK_11} --strip-components=1