FROM europe-north1-docker.pkg.dev/extender-poc/extender-public-registry/extender-base

ENV PS4_SDK_11_VERSION 11.000
ENV PS4_SDK_11  ${PLATFORMSDK_DIR}/ps4-sdk-${PS4_SDK_11_VERSION}

ENV PS4_SDK_11_FILENAME ps4-sdk-${PS4_SDK_11_VERSION}.tar.gz

RUN --mount=type=secret,id=DM_PACKAGES_URL,required=true \
  echo "PS4 ${PS4_SDK_11_FILENAME}" && \
  mkdir -p ${PS4_SDK_11} && \
  wget -q -O - $(cat /run/secrets/DM_PACKAGES_URL)/${PS4_SDK_11_FILENAME} | tar xz -C ${PS4_SDK_11} --strip-components=1