FROM europe-west1-docker.pkg.dev/extender-426409/extender-public-registry/extender-wine-env:1.4.0

# Added in version 1.4.4
ENV NINTENDO_SDK_ROOT_15_3_2=${PLATFORMSDK_DIR}/nx-15.3.2
ENV SWITCH_SDK_15_FILENAME=nx64-sdk-15.3.2.tar.gz

RUN --mount=type=secret,id=DM_PACKAGES_URL,required=true \
  echo "Switch SDK 15.3.2" && \
  mkdir -p ${NINTENDO_SDK_ROOT_15_3_2} && \
  wget -q -O - $(cat /run/secrets/DM_PACKAGES_URL)/${SWITCH_SDK_15_FILENAME} | tar xz -C ${NINTENDO_SDK_ROOT_15_3_2}