ARG EMSCRIPTEN_VERSION=4.0.6
ARG NODE_VERSION=20.18.0_64bit
ARG PLATFORMSDK_DIR=/opt/platformsdk
ARG EMSCRIPTEN_TARGET_DIR=${PLATFORMSDK_DIR}/emsdk-${EMSCRIPTEN_VERSION}
ARG EMSCRIPTEN_CONFIG=${EMSCRIPTEN_TARGET_DIR}/.emscripten
ARG EMSCRIPTEN_CACHE=/var/extender/emcache_${EMSCRIPTEN_VERSION}
ARG EMSCRIPTEN_BIN=${EMSCRIPTEN_TARGET_DIR}/upstream/emscripten

ARG EMSCRIPTEN_TEMP_DIR=/var/extender/ems_temp

FROM europe-west1-docker.pkg.dev/extender-426409/extender-public-registry/extender-build-env:1.2.0 AS build

ARG EMSCRIPTEN_VERSION
ARG NODE_VERSION
ARG EMSCRIPTEN_TARGET_DIR
ARG EMSCRIPTEN_TEMP_DIR
ARG EMSCRIPTEN_CONFIG
ARG EMSCRIPTEN_CACHE
ARG EMSCRIPTEN_BIN

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get -qq -y update \
    && apt-get -qq install -y --no-install-recommends \
        python3 \
        python3-pip

RUN --mount=type=secret,id=DM_PACKAGES_URL,required=true \
  mkdir -p "${EMSCRIPTEN_TARGET_DIR}" && \
  wget -q -O - "$(cat /run/secrets/DM_PACKAGES_URL)/emsdk-${EMSCRIPTEN_VERSION}-x86_64-linux.tar.gz" | tar xz -C "${EMSCRIPTEN_TARGET_DIR}" --strip-components=1

RUN \
  "${EMSCRIPTEN_TARGET_DIR}/emsdk" activate sdk-${EMSCRIPTEN_VERSION}-64bit && \
  EM_CONFIG="${EMSCRIPTEN_CONFIG}" EM_CACHE="${EMSCRIPTEN_CACHE}" python3 "${EMSCRIPTEN_BIN}/embuilder.py" build SYSTEM MINIMAL && \
  rm -fr "${EMSCRIPTEN_TARGET_DIR}/upstream/emscripten/tests" && \
# npm is not used by emscripten at build time; its bundled node_modules carry vulnerable packages
  rm -fr "${EMSCRIPTEN_TARGET_DIR}/node/${NODE_VERSION}/lib/node_modules/npm" \
         "${EMSCRIPTEN_TARGET_DIR}/node/${NODE_VERSION}/bin/npm" \
         "${EMSCRIPTEN_TARGET_DIR}/node/${NODE_VERSION}/bin/npx" && \
# The "sed" command below removes the /TEMP_DIR line from the generated configs
# We replace it with a folder of our own
  sed '/TEMP_DIR =/d' "${EMSCRIPTEN_CONFIG}" && \
  echo TEMP_DIR = \'${EMSCRIPTEN_TEMP_DIR}\' >> ${EMSCRIPTEN_CONFIG}


FROM europe-west1-docker.pkg.dev/extender-426409/extender-public-registry/extender-base-env:1.8.0

ARG EMSCRIPTEN_VERSION
ARG NODE_VERSION
ARG EMSCRIPTEN_TARGET_DIR
ARG EMSCRIPTEN_TEMP_DIR
ARG EMSCRIPTEN_CONFIG
ARG EMSCRIPTEN_CACHE
ARG EMSCRIPTEN_BIN

ENV EMSCRIPTEN_SDK_4_0_6=${EMSCRIPTEN_TARGET_DIR}
ENV EMSCRIPTEN_SDK=${EMSCRIPTEN_TARGET_DIR}
ENV EMSCRIPTEN_HOME_4_0_6=${EMSCRIPTEN_SDK}
ENV EMSCRIPTEN_HOME=${EMSCRIPTEN_SDK}
ENV EMSCRIPTEN_CACHE_4_0_6=${EMSCRIPTEN_CACHE}
ENV EMSCRIPTEN_CACHE=${EMSCRIPTEN_CACHE}
ENV EMSCRIPTEN_CONFIG_4_0_6=${EMSCRIPTEN_CONFIG}
ENV EMSCRIPTEN_CONFIG=${EMSCRIPTEN_CONFIG}
ENV EMSCRIPTEN_PYTHON_4_0_6=/usr/bin/python3.10
ENV EMSCRIPTEN_PYTHON=/usr/bin/python3.10
ENV EMSCRIPTEN_BIN_4_0_6=${EMSCRIPTEN_BIN}
ENV EMSCRIPTEN_BIN=${EMSCRIPTEN_BIN}
ENV EMSCRIPTEN_TEMP_DIR=${EMSCRIPTEN_TEMP_DIR}
ENV EMSCRIPTEN_PATH_4_0_6=${EMSCRIPTEN_HOME}:${EMSCRIPTEN_HOME}/upstream/bin:${EMSCRIPTEN_HOME}/node/${NODE_VERSION}/bin:${EMSCRIPTEN_BIN}
ENV EMSCRIPTEN_PATH=${EMSCRIPTEN_HOME}:${EMSCRIPTEN_HOME}/upstream/bin:${EMSCRIPTEN_HOME}/node/${NODE_VERSION}/bin:${EMSCRIPTEN_BIN}
ENV EMSDK_PYTHON=1


COPY --from=build ${EMSCRIPTEN_TARGET_DIR} ${EMSCRIPTEN_TARGET_DIR}
COPY --from=build ${EMSCRIPTEN_CACHE} ${EMSCRIPTEN_CACHE}

RUN apt-get -qq -y update && \
    apt-get -qq install -y --no-install-recommends \
    python3 \
    python-is-python3 &&\
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p ${EMSCRIPTEN_TEMP_DIR} && \
    chmod -R 755 ${EMSCRIPTEN_TARGET_DIR} && \
    chown -R extender: ${EMSCRIPTEN_CACHE} && \
    chmod -R 755 ${EMSCRIPTEN_TEMP_DIR} && \
    chown extender: ${EMSCRIPTEN_TEMP_DIR}
