ARG PLATFORMSDK_DIR=/opt/platformsdk
ARG PS4_SDK_VERSION=12.500
ARG PS4_SDK=${PLATFORMSDK_DIR}/ps4-sdk-${PS4_SDK_VERSION}

FROM europe-west1-docker.pkg.dev/extender-426409/extender-public-registry/extender-build-env:1.0.0 AS build

ARG PS4_SDK_VERSION
ARG PS4_SDK
ARG PS4_SDK_FILENAME=ps4-sdk-${PS4_SDK_VERSION}.tar.gz

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN --mount=type=secret,id=DM_PACKAGES_URL,required=true \
  mkdir -p "${PS4_SDK}" && \
  wget -q -O - "$(cat /run/secrets/DM_PACKAGES_URL)/${PS4_SDK_FILENAME}" | tar xz -C "${PS4_SDK}" --strip-components=1

FROM europe-west1-docker.pkg.dev/extender-426409/extender-public-registry/extender-wine-env:1.8.0

ARG PS4_SDK_VERSION
ARG PS4_SDK

ENV PS4_SDK_VERSION=${PS4_SDK_VERSION}
ENV PS4_SDK=${PS4_SDK}

COPY --from=build ${PS4_SDK} ${PS4_SDK}
