FROM defold/extender-base

ARG DM_PACKAGES_URL
ENV PS5_SDK_8_VERSION 8.000
ENV PS5_SDK_8  ${PLATFORMSDK_DIR}/ps5-sdk-${PS5_SDK_8_VERSION}

ENV PS5_SDK_8_FILENAME ps5-sdk-${PS5_SDK_8_VERSION}.tar.gz

RUN \
  echo "PS5 ${PS5_SDK_8_FILENAME}" && \
  mkdir -p ${PS5_SDK_8} && \
  wget -q -O - ${DM_PACKAGES_URL}/${PS5_SDK_8_FILENAME} | tar xz -C ${PS5_SDK_8} --strip-components=1