FROM europe-north1-docker.pkg.dev/extender-poc/extender-public-registry/extender-base-env

COPY users/ users/
ADD extender-0.1.0.jar app.jar
ADD manifestmergetool-0.1.0.jar $MANIFEST_MERGE_TOOL

RUN chown extender: app.jar

USER extender
ENTRYPOINT ["java","-Xmx2g","-XX:MaxDirectMemorySize=1g","-jar","/app.jar"]
