#
# Android SDK/NDK
# https://developer.android.com/studio/command-line/variables
ARG ANDROID_BUILD_TOOLS_VERSION=36.1.0
ARG ANDROID_SDK_VERSION=36
ARG ANDROID_NDK_VERSION=25b
ARG ANDROID_NDK_API_VERSION=19
ARG ANDROID_64_NDK_API_VERSION=21
ARG PLATFORMSDK_DIR=/opt/platformsdk
ARG ANDROID_ROOT=${PLATFORMSDK_DIR}/android
ARG ANDROID_HOME=${ANDROID_ROOT}/android-sdk-linux
ARG ANDROID_NDK_PATH=${ANDROID_ROOT}/android-ndk-r${ANDROID_NDK_VERSION}
ARG ANDROID_SDK_HOME=${ANDROID_ROOT}/.android
ARG ANDROID_NDK_BIN_PATH=${ANDROID_NDK_PATH}/toolchains/llvm/prebuilt/linux-x86_64/bin
ARG ANDROID_SDK_BUILD_TOOLS_PATH=${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS_VERSION}

FROM europe-west1-docker.pkg.dev/extender-426409/extender-public-registry/extender-build-env:1.1.0 AS build

ARG ANDROID_BUILD_TOOLS_VERSION
ARG ANDROID_SDK_VERSION
ARG ANDROID_SDK_FILENAME=android-sdk-linux-android-${ANDROID_SDK_VERSION}-${ANDROID_BUILD_TOOLS_VERSION}.tar.gz
ARG ANDROID_ROOT
ARG ANDROID_HOME
ARG ANDROID_NDK_PATH
ARG ANDROID_SDK_HOME
ARG ANDROID_NDK_BIN_PATH
ARG ANDROID_SDK_BUILD_TOOLS_PATH
ARG ANDROID_NDK_VERSION
ARG ANDROID_NDK_API_VERSION
ARG ANDROID_64_NDK_API_VERSION
ARG ANDROID_NDK_FILENAME=android-ndk-r${ANDROID_NDK_VERSION}-linux.tar.gz
ARG R8_VERSION=8.13.19

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN --mount=type=secret,id=DM_PACKAGES_URL,required=true \
    mkdir -p "${ANDROID_HOME}" && \
    wget -q -O - "$(cat /run/secrets/DM_PACKAGES_URL)/${ANDROID_NDK_FILENAME}" | tar xz -C "${ANDROID_ROOT}" && \
    wget -q -O - "$(cat /run/secrets/DM_PACKAGES_URL)/${ANDROID_SDK_FILENAME}" | tar xz -C "${ANDROID_HOME}" --strip-components=1 && \
    rm -rf "${ANDROID_HOME}/extras" && \
    rm -rf "${ANDROID_NDK_PATH}/prebuilt" && \
    rm -rf "${ANDROID_NDK_PATH}/simpleperf" && \
    rm -rf "${ANDROID_NDK_PATH}/shader-tools" && \
    rm -rf "${ANDROID_NDK_PATH}/sources/third_party" && \
    rm -rf "${ANDROID_NDK_PATH}/sources/cxx-stl" && \
    rm -rf "${ANDROID_NDK_PATH}/toolchains/llvm/prebuilt/linux-x86_64/i686-linux-android" && \
    rm -rf "${ANDROID_NDK_PATH}/toolchains/llvm/prebuilt/linux-x86_64/x86_64-linux-android" && \
    rm -rf "${ANDROID_NDK_PATH}/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-*" && \
    rm -rf "${ANDROID_NDK_PATH}/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-*" && \
    rm -rf "${ANDROID_NDK_PATH}/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/x86_64-linux-android" && \
    rm -rf "${ANDROID_NDK_PATH}/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/i686-linux-android" && \
# create the .android folder and give read+write permissions (the Android Gradle plugin will write to the folder)
# It is not enough to give 'user' and 'group'. We unfortunately also need 'others'
    mkdir "${ANDROID_SDK_HOME}" && \
    chmod ugo+rw -R "${ANDROID_SDK_HOME}" && \
# fix permissions
    chmod +r -R "${ANDROID_ROOT}" && \
    chmod +w -R "${ANDROID_HOME}" && \
    chmod -R 755 "${ANDROID_ROOT}/android-ndk-r${ANDROID_NDK_VERSION}" && \
    which "${ANDROID_NDK_BIN_PATH}/armv7a-linux-androideabi${ANDROID_NDK_API_VERSION}-clang++" && \
    which "${ANDROID_NDK_BIN_PATH}/aarch64-linux-android${ANDROID_64_NDK_API_VERSION}-clang++" && \
# check that aapt installed correctly
    "${ANDROID_SDK_BUILD_TOOLS_PATH}/aapt2" version && \
# download and install R8 utility separatly. It's done in that way because
# R8/D8 received fixes from time to time which not populated with build tools
# It's ok that R8.jar downloaded but saved to D8.jar. Can't find D8 as separate utility.
# R8 contains all classes of D8.
    wget -q -O "${ANDROID_SDK_BUILD_TOOLS_PATH}/lib/d8.jar" "https://storage.googleapis.com/r8-releases/raw/${R8_VERSION}/r8.jar"

FROM europe-west1-docker.pkg.dev/extender-426409/extender-public-registry/extender-android-env:1.7.0

ARG ANDROID_BUILD_TOOLS_VERSION
ARG ANDROID_SDK_VERSION
ARG ANDROID_ROOT
ARG ANDROID_HOME
ARG ANDROID_NDK_PATH
ARG ANDROID_SDK_HOME
ARG ANDROID_NDK_BIN_PATH
ARG ANDROID_SDK_BUILD_TOOLS_PATH
ARG ANDROID_NDK_VERSION
ARG ANDROID_NDK_API_VERSION
ARG ANDROID_64_NDK_API_VERSION

ENV ANDROID_ROOT=${ANDROID_ROOT} \
# ANDROID_HOME has been replaced with ANDROID_SDK_ROOT
    ANDROID_HOME=${ANDROID_HOME} \
    ANDROID_SDK_ROOT=${ANDROID_HOME} \
# ANDROID_SDK_HOME is the location of the .android folder
    ANDROID_SDK_HOME=${ANDROID_SDK_HOME} \
    ANDROID_BUILD_TOOLS_VERSION=${ANDROID_BUILD_TOOLS_VERSION} \
    ANDROID_SDK_VERSION=${ANDROID_SDK_VERSION} \
    ANDROID_SDK_BUILD_TOOLS_PATH=${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS_VERSION} \
    ANDROID_LIBRARYJAR=${ANDROID_HOME}/platforms/android-${ANDROID_SDK_VERSION}/android.jar \
# We specify it in build_input.yml by setting it the first in PATH for new SDK
# But at least one SDK should be specified by default in Dockerfile
# ANDROID_SDK_VERSION used in Java code, default should be specified in Dockerfile as well:
    ANDROID_SDK_VERSION=${ANDROID_SDK_VERSION} \
    ANDROID_NDK_VERSION=${ANDROID_NDK_VERSION} \
    ANDROID_NDK_API_VERSION=${ANDROID_NDK_API_VERSION} \
    ANDROID_64_NDK_API_VERSION=${ANDROID_64_NDK_API_VERSION} \
# These paths are the same for both the 32 and 64 bit toolchains
    ANDROID_NDK_PATH=${ANDROID_NDK_PATH} \
    ANDROID_NDK_BIN_PATH=${ANDROID_NDK_BIN_PATH} \
    ANDROID_NDK_SYSROOT=${ANDROID_NDK_PATH}/toolchains/llvm/prebuilt/linux-x86_64/sysroot \
# We specify it in build_input.yml by setting it the first in PATH
    PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_SDK_BUILD_TOOLS_PATH}:${ANDROID_NDK_BIN_PATH} \
    ANDROID_PROGUARD=/usr/share/java/proguard.jar

COPY --from=build ${ANDROID_ROOT} ${ANDROID_ROOT}

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
# android proguard was version 4.7, this is at least 5.2.1 which seems to work with OpenJDK 11
RUN \
  apt-get update && \
  apt-get install -y --no-install-recommends proguard && \
  apt-get autoremove -y && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* && \
# Since dotnet cannot really cross compile, we need to create a "ar" shim for "llvm-ar"
# As long as it's in the path, it will be picked up
  echo '#!/usr/bin/env bash' > /usr/bin/ar && \
  LLVM_AR=$(find /opt/platformsdk/android -iname "llvm-ar" | tail -1) && \
  echo "${LLVM_AR} \$*" >> /usr/bin/ar && \
  chmod +x /usr/bin/ar
