# ubuntu:22.04
FROM ubuntu@sha256:ce4a593b4e323dcc3dd728e397e0a866a1bf516a1b7c31d6aa06991baec4f2e0

RUN \
  apt-get update && \
  apt-get install -y --no-install-recommends \
    wget \
    ca-certificates \
    unzip \
    xz-utils
