ARG PLATFORMSDK_DIR=/opt/platformsdk
ARG NINTENDO_SDK_VERSION=21.4.3
ARG NINTENDO_SDK_ROOT=${PLATFORMSDK_DIR}/nx-${NINTENDO_SDK_VERSION}

FROM europe-west1-docker.pkg.dev/extender-426409/extender-public-registry/extender-build-env:1.0.0 AS build

ARG NINTENDO_SDK_VERSION
ARG NINTENDO_SDK_ROOT
ARG SWITCH_SDK_FILENAME=nx64-sdk-${NINTENDO_SDK_VERSION}.tar.gz

RUN --mount=type=secret,id=DM_PACKAGES_URL,required=true \
   mkdir -p ${NINTENDO_SDK_ROOT} && \
   wget -q -O - $(cat /run/secrets/DM_PACKAGES_URL)/${SWITCH_SDK_FILENAME} | tar xz -C ${NINTENDO_SDK_ROOT}

FROM europe-west1-docker.pkg.dev/extender-426409/extender-public-registry/extender-wine-env:1.7.0

ARG NINTENDO_SDK_VERSION
ARG NINTENDO_SDK_ROOT

ENV NINTENDO_SDK_VERSION=${NINTENDO_SDK_VERSION}
ENV NINTENDO_SDK_ROOT=${NINTENDO_SDK_ROOT}

COPY --from=build ${NINTENDO_SDK_ROOT} ${NINTENDO_SDK_ROOT}
