FROM europe-west1-docker.pkg.dev/extender-426409/extender-public-registry/extender-wine-env:1.5.0

ENV PS4_SDK_VERSION=12.500
ENV PS4_SDK=${PLATFORMSDK_DIR}/ps4-sdk-${PS4_SDK_VERSION}

ENV PS4_SDK_FILENAME=ps4-sdk-${PS4_SDK_VERSION}.tar.gz

RUN --mount=type=secret,id=DM_PACKAGES_URL,required=true \
  echo "PS4 ${PS4_SDK_FILENAME}" && \
  mkdir -p ${PS4_SDK} && \
  wget -q -O - $(cat /run/secrets/DM_PACKAGES_URL)/${PS4_SDK_FILENAME} | tar xz -C ${PS4_SDK} --strip-components=1
