FROM europe-west1-docker.pkg.dev/extender-426409/extender-public-registry/extender-wine-env:1.5.0

ENV PLATFORMSDK_WIN32=$PLATFORMSDK_DIR/Win32

ENV \
  WINDOWS_SDK_10_DIR=${PLATFORMSDK_WIN32}/WindowsKits/10 \
  WINDOWS_SDK_10_20348_VERSION=10.0.20348.0 \
  WINDOWS_MSVC_2022_VERSION=14.37.32822

ENV \
  VCINSTALLDIR_2022="${PLATFORMSDK_WIN32}/MicrosoftVisualStudio2022/VC" \
  VSINSTALLDIR_2022="${PLATFORMSDK_WIN32}/MicrosoftVisualStudio2022" \
  WINDOWS_MSVC_DIR_2022="${PLATFORMSDK_WIN32}/MicrosoftVisualStudio2022/VC/Tools/MSVC/${WINDOWS_MSVC_2022_VERSION}" \
  VS160COMNTOOLS_2022="${PLATFORMSDK_WIN32}/MicrosoftVisualStudio2022/Common7/Tools" \
  WINDOWS_VCINSTALLDIR_2022="${PLATFORMSDK_WIN32}/MicrosoftVisualStudio2022/VC/Tools/MSVC/${WINDOWS_MSVC_2022_VERSION}" \
  WINDOWS_VSINSTALLDIR_2022="${PLATFORMSDK_WIN32}/MicrosoftVisualStudio2022"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
# windres: Allows for generating .res files that can be used during linking
RUN \
  apt-get update && \
  apt-get install -y --no-install-recommends binutils-mingw-w64-x86-64 && \
  ls -la /usr/bin/x86_64-w64-mingw32-windres && \
  ln -s /usr/bin/x86_64-w64-mingw32-windres /usr/local/bin/windres && \
  rm -rf /var/lib/apt/lists/*

COPY winsdk_rename_files.py ${PLATFORMSDK_WIN32}

RUN --mount=type=secret,id=DM_PACKAGES_URL,required=true \
  mkdir -p "${PLATFORMSDK_WIN32}/MicrosoftVisualStudio2022" && \
  wget -q -O - "$(cat /run/secrets/DM_PACKAGES_URL)/Microsoft-Visual-Studio-2022-${WINDOWS_MSVC_2022_VERSION}.tar.gz" | tar xz -C "${PLATFORMSDK_WIN32}/MicrosoftVisualStudio2022" && \
  mkdir -p "${PLATFORMSDK_WIN32}/WindowsKits" && \
  wget -q -O - "$(cat /run/secrets/DM_PACKAGES_URL)/WindowsKits-${WINDOWS_SDK_10_20348_VERSION}.tar.gz" | tar xz -C "${PLATFORMSDK_WIN32}/WindowsKits" && \
  ln -s "$(which clang)" "$(dirname "$(which clang)")/x86_64-pc-win32-clang" && \
  ln -s "$(which llvm-ar)" "$(dirname "$(which llvm-ar)")/x86_64-pc-win32-clang-ar" && \
# Due to Windows' case insensitive file system, the sources reference lib files with wrong cases
# so we solve the bulk by making the suffixes lowercase. (e.g. MyLib.Lib -> MyLib.lib)
  find $PLATFORMSDK_WIN32 -iname '*.Lib' -type f -exec sh -c 'a=$(echo "$0" | sed -r "s/([^.]*)\$/\L\1/"); [ "$a" != "$0" ] && [ ! -f "$a" ] && ln -s "$0" "$a" ' {} \;

RUN \
  python ${PLATFORMSDK_WIN32}/winsdk_rename_files.py > ${PLATFORMSDK_WIN32}/rename.txt && \
# Make a copy of all the headers too, in lower case (e.g. Windows.h -> windows.h etc)
  find $PLATFORMSDK_WIN32 -iname '*.h' -type f -exec sh -c 'd=$(dirname "$0"); a=$(basename "$0" | tr [:upper:] [:lower:]); [ "$a" != $(basename "$0")  ] && [ ! -f "$d/$a" ] && ln -s "$0" "$d/$a" ' {} \; && \
# Make lower case links of libraries as well
  find ${WINDOWS_SDK_10_DIR}/Lib -iname '*.lib' -type f -exec sh -c 'd=$(dirname "$0"); a=$(basename "$0" | tr [:upper:] [:lower:]); [ "$a" != $(basename "$0")  ] && [ ! -f "$d/$a" ] && ln -s "$0" "$d/$a" ' {} \;

WORKDIR  "${WINDOWS_MSVC_DIR_2022}/lib/x64"
RUN \
# and the rest are manually copied (or made lower case)
  cp oldnames.lib OLDNAMES.lib && \
  cp libcmt.lib LIBCMT.lib && \
  cp delayimp.lib Delayimp.lib

WORKDIR "${WINDOWS_MSVC_DIR_2022}/lib/x86"
RUN \
# and the rest are manually copied (or made lower case)
  cp oldnames.lib OLDNAMES.lib && \
  cp libcmt.lib LIBCMT.lib && \
  cp delayimp.lib Delayimp.lib

# Some headers are named by the wrong name in the windows sdk's...
# We need to make certain names lowercase because some users
# have put "pragma lib" comments in some libraries :(
# and/or misspelled header files
WORKDIR "${WINDOWS_SDK_10_DIR}/Include/${WINDOWS_SDK_10_20348_VERSION}/shared"
RUN \
  cp driverspecs.h DriverSpecs.h && \
  cp specstrings.h SpecStrings.h && \
  cp concurrencysal.h ConcurrencySal.h && \
  cp wlantypes.h WlanTypes.h

WORKDIR "${WINDOWS_SDK_10_DIR}/Lib/${WINDOWS_SDK_10_20348_VERSION}/um/x64"
RUN cp psapi.lib Psapi.lib
WORKDIR "${WINDOWS_SDK_10_DIR}/Lib/${WINDOWS_SDK_10_20348_VERSION}/um/x86"
RUN cp psapi.lib Psapi.lib

# Also, the OpenGL headers in the windows SDK is in a folder with lower case letters, which doesn't match the includes
WORKDIR "${WINDOWS_SDK_10_DIR}/Include/${WINDOWS_SDK_10_20348_VERSION}/um"
RUN \
  mkdir ./GL && \
  cp -v ./gl/*.* ./GL/

WORKDIR /

# Since dotnet cannot really cross compile, we need to create a "lib" shim for "wine lib.exe"
# As long as it's in the path, it will be picked up
# hadolint ignore=SC2016
RUN \
  echo '#!/usr/bin/env bash' > /usr/bin/lib && \
  echo 'wine ${WINDOWS_VCINSTALLDIR_2022}/bin/Hostx64/x64/lib.exe $*' >> /usr/bin/lib && \
  chmod +x /usr/bin/lib