FROM europe-west1-docker.pkg.dev/extender-426409/extender-public-registry/extender-wine-env:1.5.0

ENV PS5_SDK_VERSION=12.000
ENV PS5_SDK=${PLATFORMSDK_DIR}/ps5-sdk-${PS5_SDK_VERSION}

ENV PS5_SDK_FILENAME=ps5-sdk-${PS5_SDK_VERSION}.tar.gz

RUN --mount=type=secret,id=DM_PACKAGES_URL,required=true \
  echo "PS5 ${PS5_SDK_FILENAME}" && \
  mkdir -p ${PS5_SDK} && \
  wget -q -O - $(cat /run/secrets/DM_PACKAGES_URL)/${PS5_SDK_FILENAME} | tar xz -C ${PS5_SDK} --strip-components=1
