FROM europe-west1-docker.pkg.dev/extender-426409/extender-public-registry/extender-base-env:1.8.0

ENV CLANG_VERSION=20
ENV CLANG_HOME=/usr/lib/llvm-${CLANG_VERSION}
# Possibly get the "-resource-dir" from clang++ -### empty.cpp
ENV CLANG_RESOURCE_DIR=/usr/lib/llvm-${CLANG_VERSION}/lib/clang/${CLANG_VERSION}
ENV PATH=${CLANG_HOME}/bin:$PATH
RUN \
  apt-get update && \
  apt-get install -y --no-install-recommends \
    python3 \
    python-is-python3 \
    libssl-dev \
    openssl \
    libtool \
    autoconf \
    automake \
    build-essential \
    uuid-dev \
    libxi-dev \
    libx11-xcb-dev \
    libopenal-dev \
    libgl1-mesa-dev \
    libglw1-mesa-dev \
    freeglut3-dev \
    wget \
    lsb-release \
    software-properties-common \
    gnupg && \
    wget -q https://apt.llvm.org/llvm.sh && \
    chmod +x llvm.sh && \
    ./llvm.sh ${CLANG_VERSION} && \
    rm llvm.sh && \
    apt-get remove -y wget lsb-release software-properties-common gnupg && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
