
extender:
    sdk.cache-size: 5
    cache:
        type: S3
        s3.bucket: defold-extender-cache-stage
    remote-builder:
        enabled: true
        url: https://build-darwin-stage.defold.com

endpoints:
    health:
        sensitive: true
