
server:
    port: 8080

extender:
    sdk:
        location: /usr/local/extender-production/sdk
        cache-size: 5
    cache:
        enabled: false
    remote-builder:
        enabled: false

endpoints:
    health:
        sensitive: true
