management:
    metrics:
        tags:
            application: extender
    influx:
        metrics:
            export:
                api-version: v2 # API version of InfluxDB to use. Defaults to 'v1' unless an org is configured. If an org is configured, defaults to 'v2'.
                auto-create-db: true # Whether to create the InfluxDB database if it does not exist before attempting to publish metrics to it. InfluxDB v1 only. (Default: true)
                batch-size: 10000 # Number of measurements per request to use for this backend. If more measurements are found, then multiple requests will be made. (Default: 10000)
                bucket: metrics # Bucket for metrics. Use either the bucket name or ID. Defaults to the value of the db property if not set. InfluxDB v2 only.
                compressed: true # Whether to enable GZIP compression of metrics batches published to InfluxDB. (Default: true)
                connect-timeout: 1s # Connection timeout for requests to this backend. (Default: 1s)
                consistency: one # Write consistency for each point. (Default: one)
                # db: extender # Database to send metrics to. InfluxDB v1 only. (Default: mydb)
                enabled: true # Whether exporting of metrics to this backend is enabled. (Default: true)
                num-threads: 2 # Number of threads to use with the metrics publishing scheduler. (Default: 2)
                org: defold # Org to write metrics to. InfluxDB v2 only.
                # password: mysecret # Login password of the InfluxDB server. InfluxDB v1 only.
                read-timeout: 10s # Read timeout for requests to this backend. (Default: 10s)
                # retention-policy: my_rp # Retention policy to use (InfluxDB writes to the DEFAULT retention policy if one is not specified). InfluxDB v1 only.
                step: 1m # Step size (i.e. reporting frequency) to use. (Default: 1m)
                token: "foo" # Authentication token to use with calls to the InfluxDB backend. For InfluxDB v1, the Bearer scheme is used. For v2, the Token scheme is used.
                uri: http://victoriametrics:8428 # URI of the InfluxDB server. (Default: http://localhost:8086)
                # user-name: myusername # Login user of the InfluxDB server. InfluxDB v1 only.
