
server:
    port: 8090

extender:
    sdk:
        location: /usr/local/extender-stage/sdk
        cache-size: 5
    cache:
        enabled: false
    remote-builder:
        enabled: false

endpoints:
    health:
        sensitive: true
