/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.defold.r8resources;

public final class R {
  public static final class layout {
    public static int unused_layout=0x7f010000;
    public static int used_layout=0x7f010001;
  }
  public static final class raw {
    public static int code_kept=0x7f020000;
    public static int dead_code=0x7f020001;
    public static int dynamic_kept=0x7f020002;
    public static int keep=0x7f020003;
    public static int unused=0x7f020004;
  }
  public static final class string {
    public static int code_kept=0x7f030000;
    public static int dead_code_string=0x7f030001;
    public static int manifest_kept=0x7f030002;
    public static int unused_string=0x7f030003;
    public static int xml_kept=0x7f030004;
  }
}