name: Semgrep Code Scanning

on:
  push:
    branches:
      - 'dev'
    paths:
      - '**/*.java'
      - '**/*.py'
  pull_request:
    branches:
      - 'dev'
    paths:
      - '**/*.java'
      - '**/*.py'
  schedule:
    - cron: "0 2 * * MON"

jobs:
  semgrep_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Semgrep
        run: |
          python3 -m pip install semgrep

      - name: Run Semgrep Scan
        run: |
          semgrep scan \
            --config p/java \
            --config p/security-audit \
            --sarif \
            --output semgrep-java-scan.sarif

      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@e0647621c2984b5ed2f768cb892365bf2a616ad1 # v4.37.2
        with:
          sarif_file: semgrep-java-scan.sarif
